### ISSUE TITLE
Wrong location of Duty Roster on DLC map Infiltration

### ISSUE THREAD

**Issue by NicoTh** [lordfiSh/sniperelite4maps#17]
Hey,

It seems like "Duty Roster 3: Operational Overview #C2" on thw DLC map Infiltration is marked in the wrong spot.

![image](https://user-images.githubusercontent.com/104903006/210158033-72221f51-1818-42fe-9ac5-4f0204c19281.png)

I found the OC up here.

But on your map it's marked here:

![image](https://user-images.githubusercontent.com/104903006/210158050-45cae12d-9547-4bf4-8821-45b2a98232a8.png)

**Comment by AtomCrafty** [comment]
Just double checked, you're right. I guess that officier must have followed us across half of the map. Should be fixed by d4595d9b21a6cf769e4be1bcc5c72f903fdcaba0. @lordfiSh could you update the live site?
