### ISSUE TITLE
Missing Generator Location on Giovi Fiorini Mansion

### ISSUE THREAD

**Issue by wb99999999** [lordfiSh/sniperelite4maps#18]
There's a generator that's not marked on the map in the encampment at the East side of the map, overlooking the town. It is very close to the "weakening defense" objective on that side.

There may be other missing generators since the number of generator on some maps seems a bit lower than what I remembered.

![Screenshot 2023-07-24 081127](https://github.com/lordfiSh/sniperelite4maps/assets/30381391/ad669107-d0b3-4380-9d8b-94171dab0aba)
![Screenshot 2023-07-24 081147](https://github.com/lordfiSh/sniperelite4maps/assets/30381391/26b13c0c-415a-4c57-95e0-13a57592efd7)

**Comment by AtomCrafty** [comment]
Thanks for the report! I've added this generator to the map data. Of course it's possible we missed some more generators as well, so feel free to reopen this issue if you find other discrepancies

@lordfiSh could you update the live version?
