### ISSUE TITLE
Magazzeno Facility Last Letter 2 : I Did My Duty

### ISSUE THREAD

**Issue by nemzetkoziapank** [lordfiSh/sniperelite4maps#20]
Map says it is carried by Manfred Paternoster (Officer). He is infantry

**Comment by AtomCrafty** [comment]
Interestingly, the German version says infantry, so I guess this is a simple copy/paste error. Thanks for letting us know!

**Comment by nemzetkoziapank** [comment]
You misunderstood me. He is infantry, but the map says officer:)

**Comment by AtomCrafty** [comment]
That's how I understood it the first time.

Fixed by a86a91f6e2b1cfd51d9e4e26a230a1ce3c1d9ccc. @lordfiSh please update when you get a chance.
