### ISSUE TITLE
Maybe add all the destroyable vehicles? (The only points thing missing).

### ISSUE THREAD

**Issue by Kuyoti** [lordfiSh/sniperelite4maps#4]
I just love this awesome map so much, with all its excellent information, I just wanted to express my absolute gratitude to its creators. Thank you, thank you, thank you!
It's an issue. :D

**Comment by AtomCrafty** [comment]
Glad you like it :D

Adding vehicles should be possible, the only issue I see is that not all of them are stationary.
But then again, the same is true for some mission markers.

**Comment by AtomCrafty** [comment]
Alright, after some consideration we've come to the conclusion that this would be too much work for now. If you would be willing to provide the location data, I'd be happy to add it, but at the moment we're still busy adding the markers for the remaining dlc maps.

You can get the coordinates for a map location by right clicking at the spot you want to mark and copying the `w=numbers` parameter from the url bar. It would be best to know the vehicle type for every marker, so we can display the appropriate icons.
