### ISSUE TITLE
fix map links 

### ISSUE THREAD

**Issue by lordfiSh** [lordfiSh/sniperelite4maps#6]
you can still click map links even if there disabled via `class="disabled`

![image](https://user-images.githubusercontent.com/389680/144638456-d9c5667a-5ca0-4a59-8248-968214d381da.png)

Quick fix: `<a hrefx="n/">`

![image](https://user-images.githubusercontent.com/389680/144638597-7dd3ea65-8a9c-4fb1-b2bb-444fe8d7b39e.png)

**Comment by AtomCrafty** [comment]
This is intentional. But the links seem to lead to a missing page atm.
Must be something related to the server configuration, because it works properly in my dev installation (http://se4.frucost.net/k).

It is supposed to show the map, but without any of the markers placed.
