### ISSUE TITLE
Wrong location of Letter in map

### ISSUE THREAD

**Issue by X01011010X** [lordfiSh/sniperelite4maps#9]
Hey,

Letter from Home #1: Tomorrow on Allagra Fortress is located in a wrong location of the map on your site. It's a little more to the east; the description is right, though. I hope this screenshot helps.
![LettersFromHome1_Tomorrow](https://user-images.githubusercontent.com/79312262/150669290-88a2b547-5e90-475f-af28-7fd237e7983f.png)

**Comment by AtomCrafty** [comment]
Thanks! I must have accidentally entered the coordinates of "Misc. Document 1" instead of "Letter From Home 1".
